library(tidyverse)


load("Res_MNs.Rdata")

pathways <- gmtPathways("c5.go.bp.v7.2.symbols.gmt") # GO biological process

res <- Res$FUSKO
ranklist <- res
if(length(which(is.na(res$log2FoldChange))) != 0){
  ranklist <- res[-which(is.na(res$log2FoldChange)),]
}
ranklist <- ranklist[order(ranklist$stat, decreasing=T),]
stats_ko <- as.vector(ranklist$stat)
names(stats_ko) <- rownames(ranklist)

res <- Res$FUSR495X
ranklist <- res
if(length(which(is.na(res$log2FoldChange))) != 0){
  ranklist <- res[-which(is.na(res$log2FoldChange)),]
}
ranklist <- ranklist[order(ranklist$stat, decreasing=T),]
stats_r495x <- as.vector(ranklist$stat)
names(stats_r495x) <- rownames(ranklist)

res <- Res$FUSP525Lho
ranklist <- res
if(length(which(is.na(res$log2FoldChange))) != 0){
  ranklist <- res[-which(is.na(res$log2FoldChange)),]
}
ranklist <- ranklist[order(ranklist$stat, decreasing=T),]
stats_p525lho <- as.vector(ranklist$stat)
names(stats_p525lho) <- rownames(ranklist)

res <- Res$FUSP525Lhe
ranklist <- res
if(length(which(is.na(res$log2FoldChange))) != 0){
  ranklist <- res[-which(is.na(res$log2FoldChange)),]
}
ranklist <- ranklist[order(ranklist$stat, decreasing=T),]
stats_p525lhe <- as.vector(ranklist$stat)
names(stats_p525lhe) <- rownames(ranklist)

res <- Res$TDP43M337V
ranklist <- res
if(length(which(is.na(res$log2FoldChange))) != 0){
  ranklist <- res[-which(is.na(res$log2FoldChange)),]
}
ranklist <- ranklist[order(ranklist$stat, decreasing=T),]
stats_tdp <- as.vector(ranklist$stat)
names(stats_tdp) <- rownames(ranklist)

mitogenes <- rownames(res[grep("MT-", rownames(res)),])

#### Plotting ####

plotEnrichment(pathways$GO_OXIDATIVE_PHOSPHORYLATION, stats_ko)
plotEnrichment(pathways$GO_OXIDATIVE_PHOSPHORYLATION, stats_r495x)
plotEnrichment(pathways$GO_OXIDATIVE_PHOSPHORYLATION, stats_p525lho)
plotEnrichment(pathways$GO_OXIDATIVE_PHOSPHORYLATION, stats_p525lhe)
plotEnrichment(pathways$GO_OXIDATIVE_PHOSPHORYLATION, stats_tdp)


# Note: final figure plots are edited (cut down) versions of the output plots generated by this script